In [7]:
import pandas as pd
import numpy as np

In [8]:
#preprocessing
imdb = pd.read_csv("imdb-videogames.csv")
steam = pd.read_csv("steam-200k.csv", header=None)


imdb = imdb.drop(imdb.columns[[0, 2, 3, 4, 6, 7]],axis = 1)
print(imdb.head())

steam = steam[steam.iloc[:, -3].str.contains("purchase") == False]

print(steam.head())

                         name  rating  Action  Adventure  Comedy  Crime  \
0                  Spider-Man     9.2    True       True   False  False
1      Red Dead Redemption II     9.7    True       True   False   True
2          Grand Theft Auto V     9.5    True      False   False   True
3                  God of War     9.6    True       True   False  False
4  Uncharted 4: A Thief's End     9.5    True       True   False  False

   Family  Fantasy  Mystery  Sci-Fi  Thriller
0   False     True    False   False     False
1   False    False    False   False     False
2   False    False    False   False     False
3   False    False    False   False     False
4   False    False    False   False     False
           0                           1     2      3  4
1  151603712  The Elder Scrolls V Skyrim  play  273.0  0
3  151603712                   Fallout 4  play   87.0  0
5  151603712                       Spore  play   14.9  0
7  151603712           Fallout New Vegas  play   12.1  0
9  151603712               Left 4 Dead 2  play    8.9  0

In [14]:
df2 = pd.DataFrame({'user': steam.iloc[:,0], 'games': steam.iloc[:,1],'hours': steam.iloc[:, -2]})
df2 = df2.pivot_table(index='user', columns='games', values='hours') 
df2 = df2.fillna(0)

df2.head()

games,007 Legends,0RBITALIS,1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby),10 Second Ninja,"10,000,000",100% Orange Juice,1000 Amps,12 Labours of Hercules,12 Labours of Hercules II The Cretan Bull,12 Labours of Hercules III Girl Power,...,rFactor,rFactor 2,realMyst,realMyst Masterpiece Edition,resident evil 4 / biohazard 4,rymdkapsel,sZone-Online,the static speaks my name,theHunter,theHunter Primal
user,,,,,,,,,,,,,,,,,,,,,
5250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76767,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86540,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
181212,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0